sudo: false
dist: trusty
language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - Lint/Build
  - name: Deployment
    if: branch = master

jobs:
  include:

    - stage: Lint/Build
      script:
        - npm run lint
        - npm run build

    - stage: Deployment
      env:
        - secure: UKwerxtS16CPVjYkIbrdvQttkdYPtDSgVh8s0DT9RDsPky9hff/8e2fYYqn5zt9obvPVoLpLRZ+a58DiS0C6aw48n9enfvCD/F0gQCYTEVaxpGL4RtlRBSH6HC9kCC7Xji21Ba3LvmvXmG1c3vAl67xjM4QuAPoVogS/PV35wx+S9rKcNLLrtEw536TkvBoS2NyYwSvuy9JrIvRRYz1KLs46Btqj+bWsGVSGOJ88KivqCK0c09TFp3DPquSutVBQ++OiEJYTGVWdvIJVNW52UQqi2dnfLAi+HsmY00xeiya/EzEusNONqIRBEPJh74SL3dyHoChOI3nKQdHuUdNzL0AYNvaX45f2oBVPS2wbz2P3BzMotUFPmCpLH12EDQfat1E2to9rJu564wmISLYP9o4UlAO8phxPj2ownBi9eJEdjkyWGhpktmKJNdMFLDTbLLbZr/hlQ3b6N1Ri9RGNG973wdPtcxRXdCyi0T4m3Ji1C5oQ9h8y6UJZZqgLjxsbq4r3onAccXZt7AibUdb78o1I34MbRysXT6ihKFM/mpc8OvKscnuh3HkRE/mK7RnIAsBrFkqRQMBoBvek43eyGzMYId/dNZY7uyfQ3SN55WtrZqu3/oBd6c6TTftjD35uaI5MTEd0++mwW3sEe3aMwJLWadawOZx2cuwyOV1ubMY=
        - secure: eTQB8Y7hQYBwRBsLvFVUc/NbKq2XB3EtydkEKfbK5Hxcl/MuPxvJs/GNi3cvDY7auwD94PLTr0hX4CHdCUw08DsMcSqZmjdq6NopyijO4O/GugJwTPZ+uwkDV8WBulS79PCfoU8yjQlwu0moSKzbCliR5j0Vg9rBYGSGSvmtaBjv1KMrwqwNuyJnt94pICTQTKTbkZlFWyafbPjk2bSYTIHd+iTh0Db02wqPxEoWWOu4xrVeIOXxjeBfcWUDVoTx2EREeLxsqmYOzM2R87Er45O+aMkBFfbmAd5A92b9Kl3VNbGrQeKgcFdVdjwMgOIqKKrbFfSCEd9CPOfs1x6e6LNR2pH3ibQQ4lSxGoD/40xvvDAxfL6enWPuCrJl7RpGDJ6XHnG8+4jQ6B7m9VQfqGQbAzu/i2sH/ZreMFffXk9DEaT0VHD542kzK53j53PRKDMDB6dogk46N/uQpB2mdPNZfLqbRSdMCirIvROFKlxUqzP9fH5QMHwHOohOvtg9LKTV4wGlMvP/wcchrJIwaGZqWA6pNpCag/nV25qYUbPWT+DwbfLgeRFFfjval28Dj4B4xRFFoBlfHjv+Rv0qDtuk+RzAgp2paz1/CZbuGSoTxGCGHSjkCuGRnCEjJ0k8t8H75Wth8kmQcWvJfPHl74AeysGiGXofP6E7QVZKxGc=
      script:
        - npm run deploy
